//languages
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

//Weather
export const CURRENT_WEATHER = "CURRENT_WEATHER";
export const FORECAST_WEATHER_HOURLY = "FORECAST_WEATHER_HOURLY";
export const FORECAST_WEATHER_DAILY = "FORECAST_WEATHER_DAILY";
export const ASTRONOMY = "CURRENT_WEATHER";
export const RELOCATE_DATA = "RELOCATE_DATA";

//Location
export const SEARCH_LOCATION = "SEARCH_LOCATION";
